moveit_config:
  planning_scene_monitor:
    publish_planning_scene: true
    publish_geometry_scene: true
  trajectory_execution:
    execution_timeout: 10.0
    allow_trajectory_execution: true
  planning_pipeline:
    name: ompl
    max_sampling_attempts: 1000
  request_adapters:
    - name: fix_start_state_bounds
      type: FixStartStateBounds
  joint_limits:
    joint1:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5
    joint2:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5
    joint3:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5
    joint4:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5
    joint5:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5