controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    auto_load: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    gains:
      joint_1:
        p: 10.0
        i: 0.1
        d: 0.5
      joint_2:
        p: 10.0
        i: 0.1
        d: 0.5
      joint_3:
        p: 10.0
        i: 0.1
        d: 0.5
      joint_4:
        p: 10.0
        i: 0.1
        d: 0.5
      joint_5:
        p: 10.0
        i: 0.1
        d: 0.5
    joint_limits:
      joint_1:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
      joint_2:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
      joint_3:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
      joint_4:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
      joint_5:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100  # Hz